spring:
  profiles:
    active: '@activeProfile@'
  application:
    name: customers
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: ${DB_USERNAME:tech}
    password: ${DB_PASSWORD:tech_passwd}
  jpa:
    properties:
      hibernate:
        default_schema: customers
        enable_lazy_load_no_trans: true
    show-sql: true
  flyway:
    schemas: customers
  devtools:
    add-properties: false

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger-ui-custom.html
